### ISSUE TITLE
Uses really old version of the stylesheet

### ISSUE THREAD

**Issue by evilnick** [canonical/ubuntu-core-docs#70]
I was trying to add a new table for some extra detail on community images. 

For some reason, these docs don't even use the out of date template in documentation-builder, but rather an even older version. Not sure which part (yarn I guess?) needs fixing or where it fetches the old template from.

This is what it pulls in - <style>
      /* vanilla-docs-theme 1.3.5-candidate (not yet landed - see https://github.com/vanilla-framework/vanilla-docs-theme/pull/29) */

Which is worse than -

https://github.com/canonical-webteam/documentation-builder/blob/master/ubuntudesign/documentation_builder/resources/template.html

**Comment by evilnick** [comment]
@WillMoggridge @nottrobin Any ideas what needs to get changed here?

**Comment by nottrobin** [comment]
@evilnick this is where it decides what version of documentation-builder is used by the run script:

https://github.com/canonical-docs/ubuntu-core-docs/blob/master/requirements.txt#L5

That uses version `1.5.0`. It looks like bumping that [to `1.5.1`](https://pypi.org/project/ubuntudesign.documentation-builder/) will probably give you the changes you need:

https://github.com/canonical-webteam/documentation-builder/compare/5c01ce2...2bc31f
